### ISSUE TITLE
Support new form 1099-NEC for reporting nonemployee compensation

### ISSUE THREAD

**Issue by danports** [sdj0/fire-1099#11]
Form 1099-NEC submissions are due on 31Jan2021, so I'm curious if there are plans to support this new form. Form 1099-MISC can't be used to report nonemployee compensation for tax years 2020 onwards.

**Comment by jrenaut** [comment]
I was just coming here to ask the same thing. I've tweaked the code locally and submitted a 1099-NEC to the IRS Fire test system created with my changes - will send a pull request if the IRS accepts it but bear in mind I'm a self-taught extremely mediocre coder

**Comment by danports** [comment]
Hey, if it works, I'll gladly pull your fork! 😄

**Comment by sdj0** [comment]
Hey @danports @jrenaut! As you can probably tell this isn't a super actively maintained project, regrettably. I'd love to say that I'll ship some updates in the next few days to incorporate 1099-NEC, but I'm pretty slammed.

That said, I'll absolutely take a look at a PR if you submit one! @jrenaut did you put together a JSON schema for NEC [like the one here](https://github.com/sdj0/fire-1099/blob/master/fire/schema/base_schema.json)

**Comment by jrenaut** [comment]
I copied base twice to make a MISC and a NEC version and leave the base intact, though that's probably not necessary. I can do the PR now if you want or I can wait until we see what FIRE says (though since I just submitted it yesterday afternoon, I don't expect a response until Monday at the earliest)

**Comment by sdj0** [comment]
Ah ok, makes sense to wait on the response then. I just took a look at `master` on your fork - the code updates look good to me at a glance.

Did you do any test submissions? The FIRE test system usually gives responses pretty quickly (relative to FIRE PRD, not relative to APIs in general...): https://fire.test.irs.gov/

**Comment by jrenaut** [comment]
Yeah, I made a 1099-MISC a week ago that got approved - I modified that input JSON, created a 1099-NEC ascii and submitted that yesterday afternoon. Still hasn't been processed, I don't know if a human has to get involved or if it might happen over the weekend?

**Comment by jrenaut** [comment]
IRS accepted the file last night, I'll do the pull request in a minute.

I'm curious - is there a way to confirm the information submitted? Or do I have to just trust that I did everything right?

**Comment by sdj0** [comment]
Thanks for the PR! I'll take a look today.

I was never able to find a way to see the contents of past filings, but I didn't really look outside of the FIRE system. I know for personal tax you can call the IRS and request transcripts of your past returns, wages reported to them by your employers etc. Might be worth giving them a call 🤷

**Comment by sdj0** [comment]
Just merged. Thanks again for contributing!
