### ISSUE TITLE
Support for latest 1099-NEC (as per Pub 1220 for tax year 2021)

### ISSUE THREAD

**Issue by brelkl** [sdj0/fire-1099#15]
Hi! First off, this project is great--I really appreciate the work you all have put into it! Also, I am a complete novice with github, python, and e-filing 1099-NECs. When I tried to use this app as-is, my record was rejected by the FIRE test site. Some investigation showed that the new 1099 has a slightly different structure this year--mainly, it now has 18 payment fields. So I made a few changes to the code to accommodate this new structure, and the FIRE test site now validates my submission as 'good'. I was wondering if you'd like to review them for possible merging? I haven't yet forked your repo on github (was working locally), so I'll work on getting that done.

**Comment by sdj0** [comment]
Hello! Thanks for taking the time to drop by and comment. I would love it if you could PR your changes so I can merge them to the main branch. No doubt others would find the fix/update to the new IRS spec useful (I wasn't aware they changed it).

**Comment by brelkl** [comment]
OK, PR created. I also verified that the FIRE production system gave me a 'good' result with these changes to the format. Thanks!

**Comment by sdj0** [comment]
Closed in #16
