### ISSUE TITLE
Is this for Linux only? Would a video tutorial be too much to ask for?

### ISSUE THREAD

**Issue by MaximilianKohler** [sdj0/fire-1099#22]
Seems like just what I was looking for, but I don't understand the directions for how to use it. Eg: "clone this repository and run the following command from the repository root directory".

**Comment by sdj0** [comment]
This isn't for Linux only, but it's only been tested on MacOS and Linux as far as I know. However there is no graphical UI - it is command line only at the moment.

All that said, having a GIF or video walkthrough of setting it up and running it isn't a bad idea. There are a few other issues in the queue but I'll try to put that together at some point!

Edit: in the meantime, here's a more detailed sequence of commands for setting up and running the tool on OSX. Should be nearly identical in Linux - I don't have access to a Windows machine so can't test a translation of these unfortunately:

```zsh
mkdir firedemo
cd firedemo/

conda create -n firedemo
conda activate firedemo

git clone https://github.com/sdj0/fire-1099
cd fire-1099/
ls -al

pip install .

fire-1099 spec/data/valid_all_MISC.json --output ./out.ascii
```

EDIT: the `conda` steps are optional; meant for people using Anaconda to manage Python environments.

**Comment by MaximilianKohler** [comment]
I can test a Windows translation. But regarding the GIF/video it might not be necessary since the IRS just told me they're planning on releasing a way for us to do this ourselves through their website.

**Comment by sdj0** [comment]
Oh interesting, do you have any more info on what that feature would entail or when it'll be available?

**Comment by MaximilianKohler** [comment]
This is all they told me so far:
>The IRS is currently working on fill-in form formats for future deployment. You may want to sign up for IRS Quick Alerts at [irs.gov](http://irs.gov/) to stay informed.

That was in reply to my query:
>Do I understand correctly that the only way to file a 1099-NEC electronically is to buy expensive 3rd party software to convert/create a unique file type? The amount of information contained in a 1099-NEC is extremely minimal and should be trivial to type in on your website. Yet you don't allow that? I just spent a month trying to get into your complex online system for nothing?

I followed up to ask how soon it might be expected. Should hear back next week.

**Comment by sdj0** [comment]
> The amount of information contained in a 1099-NEC is extremely minimal and should be trivial to type in on your website.

This really summarizes the frustration that led me to start this project 😆 

Thanks for providing this info. I'm curious to hear if the IRS does offer up a timeline or specifics on what the UI would be for fill-in formats. Ideally it eventually renders this project irrelevant.

**Comment by MaximilianKohler** [comment]
Well they still haven't gotten back to me, so if there are some Windows commands I can test I'd be happy to do that.

**Comment by MaximilianKohler** [comment]
I checked with my friend who's familiar with linux and he said:

> that isn't linux. that is python. you can install python on windows and run python commands inside of windows powershell or cmdline. I recommend "Windows Terminal" from the microsoft store. Make sure to read the instructions carefully and install the correct version of python.
> python is cross-platform.
> 
> if you think it easier to do in linux, you can simply install WSL (windows subsystem linux), Debian. Also in the microsoft store.
> it's like an easy setup virtual machine.

So I installed **python** and **windows terminal**. You also need to install **git**. 

I started with the commands above that you gave. 

>mkdir firedemo
> cd firedemo/

These two didn't seem necessary though, since the next command:
>git clone https://github.com/sdj0/fire-1099

Creates another folder where everything seems to be done: "fire-1099"

I then did "cd fire-1099/", and then I got errors for the next commands:

> ls -al
> pip install .

![pip install](https://user-images.githubusercontent.com/3606996/158546547-5af7959c-94f7-4440-bc05-865807f5ef3e.png)

Here's the solution: https://stackoverflow.com/questions/36835341/pip-is-not-recognized

"pip install ." worked after that. But "ls -al" still gave an error. 

I then put the valid-minimal.json into fire-1099 folder (renamed it to MISC.json), and ran: 

>fire-1099 MISC.json --output MISC.ascii --type NEC

But that didn't seem to work. It results in a "how do you want to open this file" popup, and I selected notepad, and the contents are:
```
#!/usr/bin/env python

"""
Main entrypoint
"""

from fire.translator import cli

cli()
```

and it's saving that file to C:\Users\User1\AppData\Local\Programs\Python\Python310\Scripts
without the .ascii

I also tried:
MISC.json --output MISC.ascii --type NEC
fire-1099/MISC.json --output MISC.ascii --type NEC
fire-1099 C:\Users\User1\Downloads\fire-1099\MISC.json --output C:\Users\User1\Downloads\fire-1099\MISC.ascii --type NEC

The first two give and error, and the 3rd does the same thing as "fire-1099 MISC.json --output MISC.ascii --type NEC". 

I'm going to try installing windows subsystem linux and report back.

**Comment by MaximilianKohler** [comment]
Tried booting to **Puppy Linux** from USB, but the commands weren't working:

```
root# pip install .
bash: pip: command not found

root# fire-1099 NEC.json --output NEC.ascii --type NEC
bash: fire-1099: command not found
```

Installed WSL (**windows subsystem linux**) and **Debian**. Installed **filezilla** in order to get access to the files. 

Had to do these commands in Debian to get a connection with filezilla:
```
sudo apt-get update && sudo apt-get upgrade -y
apt-cache search ssh
sudo apt-get install openssh-server
sudo service ssh start
ip add
```

Copy the IP from the line similar to: "inet **172.11.214.31**/20 brd 172.11.255.255 scope global eth0"
![11145860 295_image](https://user-images.githubusercontent.com/3606996/158628204-eab5ccd8-b6f5-4986-a42a-ae8185cae964.png)
![11190097 77_image](https://user-images.githubusercontent.com/3606996/158626792-715dbf75-4007-4790-bd7e-12ef87fa71ca.png)

Then:
`sudo apt-get install python3-pip`

But when I put 
`fire-1099 NEC.json --output NEC.ascii --type NEC` I get `/usr/bin/env: ‘python\r’: No such file or directory`. 

Tried the directions here https://askubuntu.com/questions/896860/usr-bin-env-python3-r-no-such-file-or-directory 
```
sudo apt install dos2unix
find . -type f -print0 | xargs -0 dos2unix
```

Didn't work unfortunately. 

Friend who helped me with all of that suggested:

>maybe just set the top like to !#/usr/bin/python instead of python env
>i mean the fireproof program or whatever is just a script in /usr/bin . you can edit it
might not work but idk

~~But I'm not sure how to do that~~. Didn't seem to do anything. 
I saw some directions before to use "python3" instead of "python" in some instances. So I tried:
#!/usr/bin/env python3
and 
#!/usr/bin/python3

But they both gave the same error which makes me think Debian's not reading the updated file or I'm in the wrong folder. I was editing the top line of "fire-1099" in "fire-1099\bin". But I also looked in this other bin folder:
![bin](https://user-images.githubusercontent.com/3606996/158632054-4f10a5db-ebf7-4902-b4ae-275e6cdabffa.png)

**Comment by mreddy614** [comment]
Here is one way to create the output file in windows after installing python and cloning the repository:

- Open Cmd prompt in windows
- cd to fire-1099 directory
- open python interperter by typing python
- at the >>> prompt type the following:
     >>> from fire.translator.translator import run
     >>> run("./spec/data/valid_all_MISC.json", "outputsample.ascii")
    >>> quit()
- outputsample.ascii will contain the output file.
- You can type content out(i.e type outputsample,ascii) to see the contents on Cmd prompt.

Below is a sample execution of these commands in windows at Cmd prompt:

C:\Python34\fire-1099>python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from fire.translator.translator import run
>>> run("./spec/data/valid_all_MISC.json", "outputsample.ascii")
>>> quit()

C:\Python34\fire-1099>type outputsample.ascii
T201712345678955AA5TXASDF GLOBAL INCASDF GLOBAL INC123 ASDF STREETNEW YORKNY1000100000002RONALD SWANSON5555555555ronald@swanson.com000000011GSG CORP1234 POIU StTAXVILLETX10991BLERD FLERPLERMERD55577766661A20171123456789ASDF1A123456789ABCDEFG1ASDF GLOBAL INC123 ASDF STREETNEW YORKNY10001555555555500000002B2017SPAC1987654321000000000100000000000200000000000300000000000400000000000500000000000600000000000700000000000800000000000900000000001000000000001100000000001200000000001300000000001400000000001500000000001600000000000000000000000000SPACELEY SPROCKETS5678 INDUSTRY PLACEMOONCA2222200000003B2017BOBL1098765432000000001600000000001500000000001400000000001300000000001200000000001100000000001000000000000900000000000800000000000700000000000600000000000500000000000400000000000300000000000200000000000100000000000000000000000000BOB LOBLAW LLP100 LAWBOMB RDBLOBVILLECA1111100000004C0000000200000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000000000000000000000000000000005F000000010000000000000000000000000000200000006

**Comment by MaximilianKohler** [comment]
That didn't work unfortunately:
![python commands](https://user-images.githubusercontent.com/3606996/158718082-43f3a2bc-707a-4c53-bb51-ac2e75753645.png)

When I do "pip install ." it gives this info, which perhaps is the problem:
```
 WARNING: The script jsonschema.exe is installed in 'C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
    Running setup.py install for fire-1099 ... done
Successfully installed attrs-21.4.0 click-8.0.4 colorama-0.4.4 fire-1099-0.0.1a0 jsonschema-4.4.0 pyrsistent-0.18.1
PS C:\Users\User1\firedemo\fire-1099>
```
~~Not sure how to "add directory to PATH"~~. I added it https://www.c-sharpcorner.com/article/add-a-directory-to-path-environment-variable-in-windows-10/

That seems to have worked...
![output sample](https://user-images.githubusercontent.com/3606996/158719989-b3f9b9d0-9c28-4a49-9de5-41072c6b75ec.png)

Also, it doesn't use the "--type NEC", which is important no?

It only seems to work with valid_all_MISC.json. Is there a way to get it to work with valid-minimal.json?

I'm wondering if it's easy enough to just edit the ascii output?

**Comment by mreddy614** [comment]
The output is written to a file named outputsample.ascii. Check you directory, that file will be there.

As for NEC, you need to create a json file for NEC. For test purposes copy valid_all_MISC.json file in the spec/data folder to valid_all_NEC.json and run the the following:

C:\Python34\fire-1099>python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from fire.translator.translator import run
>>> run("./spec/data/valid_all_NEC.json", "outputsampleNEC.ascii", "NEC")
>>> quit()

C:\Python34\fire-1099>type outputsampleNEC.ascii
T201712345678955AA5TXASDF GLOBAL INCASDF GLOBAL INC123 ASDF STREETNEW YORKNY1000100000002RONALD SWANSON5555555555ronald@swanson.com000000011GSG CORP1234 POIU StTAXVILLETX10991BLERD FLERPLERMERD55577766661A20171123456789ASDF1A123456789ABCDEFG1ASDF GLOBAL INC123 ASDF STREETNEW YORKNY10001555555555500000002B2017SPAC1987654321000000000100000000000200000000000300000000000400000000000500000000000600000000000700000000000800000000000900000000001000000000001100000000001200000000001300000000001400000000001500000000001600000000000000000000000000SPACELEY SPROCKETS5678 INDUSTRY PLACEMOONCA2222200000003B2017BOBL1098765432000000001600000000001500000000001400000000001300000000001200000000001100000000001000000000000900000000000800000000000700000000000600000000000500000000000400000000000300000000000200000000000100000000000000000000000000BOB LOBLAW LLP100 LAWBOMB RDBLOBVILLECA1111100000004C0000000200000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000000000000000000000000000000005F000000010000000000000000000000000000200000006

**Comment by mreddy614** [comment]
The output is written to outputsampleNEC.ascii file. 

Disclaimer: I have not verified if this output is valid.

**Comment by MaximilianKohler** [comment]
Thanks a lot mreddy614! 

I had edited my previous comment a few times. I'm wondering if there a way to get it to work with valid-minimal.json? valid_all_MISC.json has a lot of excess stuff that complicates things. But maybe I can get it to work by just deleting the excess stuff. 

For instance, I'm trying to remove "vendor_indicator". But these all result in an error:
>"vendor_indicator": "",
>"vendor_indicator": "0",

```
>>> run("./spec/data/valid_all_NEC.json", "outputsampleNEC.ascii", "NEC")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User1\firedemo\fire-1099\fire\translator\translator.py", line 66, in run
    validate_user_data(user_data, schema_path)
  File "C:\Users\User1\firedemo\fire-1099\fire\translator\translator.py", line 111, in validate_user_data
    validate(data, schema)
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jsonschema\validators.py", line 1022, in validate
    raise error
jsonschema.exceptions.ValidationError: '' does not match '^[a-zA-Z]{2}$'

Failed validating 'pattern' in schema['properties']['transmitter']['properties']['vendor_state']:
    {'pattern': '^[a-zA-Z]{2}$', 'type': 'string'}

On instance['transmitter']['vendor_state']:
    ''
>>> run("./spec/data/valid_all_NEC.json", "outputsampleNEC.ascii", "NEC")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\User1\firedemo\fire-1099\fire\translator\translator.py", line 66, in run
    validate_user_data(user_data, schema_path)
  File "C:\Users\User1\firedemo\fire-1099\fire\translator\translator.py", line 111, in validate_user_data
    validate(data, schema)
  File "C:\Users\User1\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\jsonschema\validators.py", line 1022, in validate
    raise error
jsonschema.exceptions.ValidationError: '' does not match '^[a-zA-Z]{2}$'

Failed validating 'pattern' in schema['properties']['transmitter']['properties']['vendor_state']:
    {'pattern': '^[a-zA-Z]{2}$', 'type': 'string'}

On instance['transmitter']['vendor_state']:
    ''
```

Deleting these lines completely seems to work...

```
,
	    "vendor_indicator": "",
	    "vendor_name": "",
	    "vendor_mailing_address": "",
	    "vendor_city": "",
	    "vendor_state": "",
	    "vendor_zip_code": "",
	    "vendor_contact_name": "",
	    "vendor_contact_telephone_and_ext": "",
	    "vendor_foreign_entity_indicator": ""
```

I seem to have been able to get it to work with valid-minimal.json too _(it was the addition of "NEC" in the cmd that did it `run("min_NEC.json", "outputminNEC.ascii", "NEC")`)_. Thanks so much for your help!

**Comment by mreddy614** [comment]
Here is one way to create the output file in windows after installing python and cloning the repository:

- Open Cmd prompt in windows
- cd to fire-1099 directory
- open python interperter by typing python
- at the >>> prompt type the following:
     >>> from fire.translator.translator import run
     >>> run("./spec/data/valid_all_MISC.json", "outputsample.ascii")
    >>> quit()
- outputsample.ascii will contain the output file.
- You can type content out(i.e type outputsample,ascii) to see the contents on Cmd prompt.

Below is a sample execution of these commands in windows at Cmd prompt:

C:\Python34\fire-1099>python
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
>>> from fire.translator.translator import run
>>> run("./spec/data/valid_all_MISC.json", "outputsample.ascii")
>>> quit()

C:\Python34\fire-1099>type outputsample.ascii
T201712345678955AA5TXASDF GLOBAL INCASDF GLOBAL INC123 ASDF STREETNEW YORKNY1000100000002RONALD ***@***.*** CORP1234 POIU StTAXVILLETX10991BLERD FLERPLERMERD55577766661A20171123456789ASDF1A123456789ABCDEFG1ASDF GLOBAL INC123 ASDF STREETNEW YORKNY10001555555555500000002B2017SPAC1987654321000000000100000000000200000000000300000000000400000000000500000000000600000000000700000000000800000000000900000000001000000000001100000000001200000000001300000000001400000000001500000000001600000000000000000000000000SPACELEY SPROCKETS5678 INDUSTRY PLACEMOONCA2222200000003B2017BOBL1098765432000000001600000000001500000000001400000000001300000000001200000000001100000000001000000000000900000000000800000000000700000000000600000000000500000000000400000000000300000000000200000000000100000000000000000000000000BOB LOBLAW LLP100 LAWBOMB RDBLOBVILLECA1111100000004C0000000200000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000170000000000000000000000000000000000000000000005F000000010000000000000000000000000000200000006


________________________________

**Comment by sdj0** [comment]
thanks @mreddy614 ! This is great and could be useful for others on Windows. I'll keep the issue open as a reminder to incorporate this guidance into the README at some point.

**Comment by mreddy614** [comment]
Thank you, any chance the enhancement request can be implemented for this year?

On Oct 14, 2022, at 11:40 AM, stephen johnson ***@***.***> wrote:

﻿

thanks @mreddy614<https://github.com/mreddy614> ! This is great and could be useful for others on Windows. I'll keep the issue open as a reminder to incorporate this guidance into the README at some point.

**Comment by MaximilianKohler** [comment]
>it might not be necessary since the IRS just told me they're planning on releasing a way for us to do this ourselves through their website.
>This is all they told me so far:
>The IRS is currently working on fill-in form formats for future deployment. You may want to sign up for IRS Quick Alerts at [irs.gov](http://irs.gov/) to stay informed.

Looks like their new system is IRIS https://github.com/sdj0/fire-1099/issues/31
