### ISSUE TITLE
fire-1099 binary -> add shebang?

### ISSUE THREAD

**Issue by gregsadetsky** [sdj0/fire-1099#7]
I had trouble running [fire-1099](https://github.com/sdj0/fire-1099/blob/master/bin/fire-1099) right out of the gate (after doing `pip install .`) as the binary was seen (on my osx machine) as a bash executable.

Adding `#!/usr/bin/env python` at the top of the file solved this issue.

**Comment by sdj0** [comment]
Going back to some of these stale issues since this repo has had some recent activity. Commit https://github.com/sdj0/fire-1099/commit/d70f71813a76dc23ccbd5a751a70cd927e6db1be includes this fix. Thanks @gregsadetsky for pointing this out!
