### ISSUE TITLE
some spec/data/*.json files are not valid

### ISSUE THREAD

**Issue by gregsadetsky** [sdj0/fire-1099#8]
Running `fire-1099` over the spec/data/*.json files results in the following:

- `valid_all.json` is valid
- `valid_minimal.json` raises an Exception:

`'first_payee_name_line' is a required property`

- `valid_standard.json` raises an Exception:

`'first_payee_name_line' is a required property`

- `valid_transmitter.json` raises an Exception:

```
  File "/usr/local/lib/python3.7/site-packages/fire/translator/translator.py", line 124, in load_full_schema
    merged_data["payer"] = payer.xform(data["payer"])
KeyError: 'payer'
```

**Comment by sdj0** [comment]
@gregsadetsky thanks for bringing these to my attention! After some investigation (a couple years later, regrettably.... 😬 ). It looks like I introduced some bugs in the test data at some point. 

> valid_minimal.json
> valid_standard.json

There was a field incorrectly named `payee_name` and the `payment_amount_1` field wasn't being used correctly in these. Both files corrected in https://github.com/sdj0/fire-1099/pull/14

> valid_transmitter.json

This one was actually never meant to be used as a standalone file to run through the `fire-1099` binary. `Transmitter` is one of the properties / sections of the body in the broader form types, and this was just meant to provide some test data for those sections.
